name: arsl_application
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: 0.11.0+2
  #tflite_flutter: ^0.9.0
  #tflite_flutter_helper: ^0.3.0
  image_picker: ^0.8.7
  tflite: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_blue: ^0.8.0  # Bluetooth Library
  flutter_lints: ^5.0.0
  speech_to_text: ^5.0.0  # speech_to_text library

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/test.jpg
    - assets/labels-arabic.txt
    #- assets/trained_model_v2.tflite
